method: metaavatar
data:
  path: data/AMASS
  dataset: cape_corr
  use_aug: false
  normalized_scale: false
  train_split: train
  val_split: val
  test_split: test
  train_views: null
  val_views: null
  test_views: null
  num_fg_samples: 1024
  num_bg_samples: 1024
  train_subsampling_rate: 1
  train_start_frame: 0
  train_end_frame: 0
  val_subsampling_rate: 30
  val_start_frame: 0
  val_end_frame: 0
  test_subsampling_rate: 30
  test_start_frame: 0
  test_end_frame: 0
  views: []
  off_surface_thr: 0.2
  inside_thr: 0.001
  box_margin: 0.05
  sampling: default
  erode_mask: true
  sample_reg_surface: false
  pose_dir: MPI-Limits_03009_op8_poses
  high_res: false
model:
  decoder: hyper_bvp
  encoder: null
  decoder_kwargs: {}
  renderer: 'mlp'
  renderer_kwargs: {'mode': idr, 'd_in': 9, 'd_out': 3, 'd_hidden': 256, 'n_layers': 4, 'weight_norm': true, 'multires': 0, 'multires_view': 4, 'squeeze_out': true}
  encoder_kwargs: {}
  latent_dim: 128
  train_cameras: false
  train_smpl: true
  geometry_net: null
  skinning_net1: null
  skinning_net2: null
  color_pose_encoder: null
  geo_pose_encoder: null
  cano_view_dirs: true
  n_steps: 64
  near_surface_samples: 16
  far_surface_samples: 16
  render_last_pt: false
training:
  out_dir:  out/default
  batch_size: 1
  checkpoint_every_n_epochs: 10
  validate_every_n_epochs: 20
  max_epochs: 250
  lr: 1.0e-6
  skinning_lr: 1.0e-4
  pose_net_factor: 100
  rgb_weight: 3.0e+1
  perceptual_weight: 0.0
  eikonal_weight: 5.0e+1
  mask_weight: 3.0e+3
  off_surface_weight: 1.0e+2
  inside_weight: 0.0
  params_weight: 1.0e+2
  skinning_weight: 0.0
  gpus: [0]
  train_skinning_net: false
  rgb_loss_type: l1
  pose_input_noise: false
  view_input_noise: false
  nv_noise_type: rotation
